### ISSUE TITLE
Re-filled watched inbox gives error

### ISSUE THREAD

**Issue by kaefer3000** [uvdsl/solid-inbox-watcher#7]
An inbox that has been emptied and re-filled gives an error that smells like there is some unexpected XML or HTML sent to a RDF parser.

Steps to reproduce:
* Watch an empty inbox
* Add a resource to the inbox
* Delete this resource
* Add another resource
![pastedImage](https://user-images.githubusercontent.com/6708974/151708637-52d60c06-1fa7-44b2-a291-32636a4b9d42.png)

**Comment by uvdsl** [comment]
Could not reproduce that exact error, but got another one, which is adressed in  650721f4a67a1844f49498ea45f1051679d51960.
Does this commit resolve your issue as well?

**Comment by uvdsl** [comment]
If this error still occurs, please reopen this issue.
